# -*- coding: utf-8 -*-
"""kidswithcandies.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1trC2o4-XQdFUkdhSz8BOw-6GT8IIAL1w
"""

class Solution:
    def kidsWithCandies(self, candies, extraCandies):
        max_candies = max(candies)
        result = []
        for candy in candies:
            result.append(candy + extraCandies >= max_candies)
        return result
solution = Solution()
candies = [2, 3, 5, 1, 3]
extraCandies = 3
print(solution.kidsWithCandies(candies, extraCandies))